{
 "title": "Solr Dashboard",
 "description": "Solr Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "collection",
    "query": {
     "query": "label_values(solr_metrics_core_distrib_select_one_minute_rate{collection=~\".+\"},collection)"
    }
   },
   {
    "name": "shard",
    "query": {
     "query": "label_values(solr_metrics_core_distrib_select_one_minute_rate{collection=~\"$collection\",shard=~\".+\"},shard)"
    }
   },
   {
    "name": "replica",
    "query": {
     "query": "label_values(solr_metrics_core_distrib_select_one_minute_rate{collection=~\"$collection\",shard=~\"$shard\",replica=~\".+\"},replica)"
    }
   },
   {
    "name": "core",
    "query": {
     "query": "label_values(solr_metrics_core_distrib_select_one_minute_rate,core)"
    }
   },
   {
    "name": "base_url",
    "query": {
     "query": "label_values(solr_ping{base_url=~\".+\"},base_url)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Core Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Documents",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (collection) (avg by (shard, collection) (solr_metrics_core_searcher_documents{collection=~\"$collection\", item=~\"numDocs\"}))",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Number of Replicas per Shard",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(count by (replica) (solr_metrics_core_distrib_select_one_minute_rate{collection=~\"$collection\", handler=\"/select\", item=\"1minRate\"}))",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Overall Select Requests Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (solr_metrics_core_distrib_one_minute_rate{collection=~\"$collection\", handler=\"/select\", item=\"1minRate\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Average Select Requests Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (solr_metrics_core_distrib_one_minute_rate{collection=~\"$collection\", handler=\"/select\", item=\"1minRate\"}) / count(count by (replica) (solr_metrics_core_distrib_select_one_minute_rate{collection=~\"$collection\", handler=\"/select\", item=\"1minRate\"}))",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Select Requests Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_distrib_one_minute_rate{collection=~\"$collection\", handler=\"/select\", item=\"1minRate\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    }
   ]
  },
  {
   "title": "Overall Update Requests Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (collection) (solr_metrics_core_distrib_one_minute_rate{collection=~\"$collection\", handler=\"/update\", item=\"1minRate\"})",
     "legendFormat": "{{collection}}"
    }
   ]
  },
  {
   "title": "Overall Select Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (collection, item) (solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/select\", item=\"median_ms\"})",
     "legendFormat": "{{collection}} {{item}}"
    },
    {
     "expr": "max by (collection, item) (solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/select\", item=\"p99_ms\"})",
     "legendFormat": "{{collection}} {{item}}"
    },
    {
     "expr": "max by (collection, item) (solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/select\", item=\"p95_ms\"})",
     "legendFormat": "{{collection}} {{item}}"
    }
   ]
  },
  {
   "title": "Overall Update Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (collection, item) (solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/update\", item=\"median_ms\"})",
     "legendFormat": "{{collection}} {{item}}"
    },
    {
     "expr": "max by (collection, item) (solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/update\", item=\"p99_ms\"})",
     "legendFormat": "{{collection}} {{item}}"
    },
    {
     "expr": "max by (collection, item) (solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/update\", item=\"p95_ms\"})",
     "legendFormat": "{{collection}} {{item}}"
    }
   ]
  },
  {
   "title": "Select Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/select\", item=\"mean_ms\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    },
    {
     "expr": "solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/select\", item=\"p95_ms\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    },
    {
     "expr": "solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/select\", item=\"p99_ms\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    }
   ]
  },
  {
   "title": "Update Request Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/update\", item=\"mean_ms\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    },
    {
     "expr": "solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/update\", item=\"p95_ms\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    },
    {
     "expr": "solr_metrics_core_distrib_latency{collection=~\"$collection\", handler=\"/update\", item=\"p99_ms\"}",
     "legendFormat": "{{core}}{{handler}} {{item}}"
    }
   ]
  },
  { "title": "JVM Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Heap Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{item=\"committed\"}",
     "legendFormat": "{{item}}"
    },
    {
     "expr": "solr_metrics_jvm_memory_heap_bytes{item=\"used\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "GC Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_total{}[1m])",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "GC Time Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_gc_seconds_total{}[1m])",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_node_core_root_fs_bytes{}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  { "title": "OS Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "solr_metrics_jvm_os_cpu_load{}", "legendFormat": "{{item}}" }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_load_average{}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "Memory Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{item=\"freePhysicalMemorySize\"}",
     "legendFormat": "{{item}}"
    },
    {
     "expr": "solr_metrics_jvm_os_memory_bytes{item=\"totalPhysicalMemorySize\"}",
     "legendFormat": "{{item}}"
    }
   ]
  },
  {
   "title": "CPU Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(solr_metrics_jvm_os_cpu_time_seconds{}[1m])",
     "legendFormat": "{{item}}"
    }
   ]
  }
 ]
}