apiVersion: "v1"
kind: "Service"
metadata:
  name: solr-exporter-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}
  annotations:
    prometheus.io/port: "9983"
    prometheus.io/scrape: "true"
spec:
  type: "ClusterIP"
  ports:
  - port: 9983
    name: "solr-client"
  selector:
    app: solr-{{ .Values.clusterId }}