apiVersion: v1
kind: Service
metadata:
  name: solr-external-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}
spec:
  type: LoadBalancer
  ports:
    - port: 8983
      targetPort: 8983  
  selector:
    app: solr-{{ .Values.clusterId }}