apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: solr-pdb-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: solr-{{ .Values.clusterId }}
  maxUnavailable: 1