---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: solr-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}
  name: solr-{{ .Values.namespace }}
rules:
  - apiGroups: [""]
    resources: [ "nodes" ]
    verbs: [ "get" ]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}
  name: solr-{{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: solr-{{ .Values.clusterId }}
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: solr-{{ .Values.namespace }}
  apiGroup: rbac.authorization.k8s.io