apiVersion: v1
kind: Service
metadata:
  name: solr-hs-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}
spec:
  ports:
  - port: 8983
    name: http-solr-hs
  # We want all pods in the StatefulSet to have their addresses published
  # so that nodes can talk to each other before the readiness probes can pass
  publishNotReadyAddresses: true
  clusterIP: None
  selector:
    app: solr-{{ .Values.clusterId }}