apiVersion: v1
kind: Service
metadata:
  name: solr-cs-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: solr-{{ .Values.clusterId }}
spec:
  ports:
  - port: 80
    name: http-solr-cs
    targetPort: 8983
  selector:
    app: solr-{{ .Values.clusterId }}