apiVersion: v1
kind: Service
metadata:
  name: zk-cs-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: zk-{{ .Values.clusterId }}
spec:
  ports:
  - port: 2181
    name: client
  selector:
    app: zk-{{ .Values.clusterId }}