apiVersion: v1
kind: Service
metadata:
  name: zk-external-{{ .Values.clusterId }}
  namespace: {{ .Values.namespace }}
  labels:
    app: zk-{{ .Values.clusterId }}
spec:
  type: LoadBalancer
  ports:
    - port: 2181
      targetPort: 2181  
  selector:
    app: zk-{{ .Values.clusterId }}